<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref } from "vue";

type Status = "active" | "archived";
type Cohort = { id: string; label: string; year: number | null; sortOrder: number };
type Person = { id: string; name: string; nickname: string | null; avatarUrl: string | null; cohort: Cohort | null; relationScope: "lineage" | "cohort_guest"; isFeatured: boolean; status: Status; mentorId: string | null; depth: number | null; directStudentIds: string[]; role: string; joinedAt: string; tags: string[]; bio: string };
type Edge = { id: string; mentorId: string; studentId: string };
type Tree = { rootPersonId: string | null; nodes: Person[]; edges: Edge[]; generatedAt: string; demo: boolean };

const fallbackPeople: Person[] = [
  { id: "demo-person-001", name: "林砚", nickname: "砚叔", avatarUrl: null, cohort: { id: "cohort-2019", label: "2019 · 初始谱系", year: 2019, sortOrder: 0 }, relationScope: "lineage", isFeatured: true, status: "active", mentorId: null, depth: 0, directStudentIds: ["demo-person-002", "demo-person-003"], role: "发起人 / 产品顾问", joinedAt: "2019-06-18", tags: ["产品", "社区"], bio: "从一张白纸开始，记录每一次认真连接。" },
  { id: "demo-person-002", name: "周予安", nickname: null, avatarUrl: null, cohort: { id: "cohort-2021", label: "2021 · 春季届", year: 2021, sortOrder: 1 }, relationScope: "lineage", isFeatured: false, status: "active", mentorId: "demo-person-001", depth: 1, directStudentIds: ["demo-person-004", "demo-person-005"], role: "全栈开发者", joinedAt: "2021-03-22", tags: ["工程", "开源"], bio: "喜欢把复杂的问题拆成可以一起走的路。" },
  { id: "demo-person-003", name: "许棠", nickname: null, avatarUrl: null, cohort: { id: "cohort-2021", label: "2021 · 春季届", year: 2021, sortOrder: 1 }, relationScope: "lineage", isFeatured: false, status: "active", mentorId: "demo-person-001", depth: 1, directStudentIds: ["demo-person-006"], role: "研究与内容", joinedAt: "2021-04-08", tags: ["研究", "写作"], bio: "在资料、田野和人之间，寻找能被传下去的东西。" },
  { id: "demo-person-004", name: "苏禾", nickname: null, avatarUrl: null, cohort: { id: "cohort-2023", label: "2023 · 秋季届", year: 2023, sortOrder: 2 }, relationScope: "lineage", isFeatured: false, status: "active", mentorId: "demo-person-002", depth: 2, directStudentIds: [], role: "交互设计师", joinedAt: "2023-09-01", tags: ["设计", "体验"], bio: "让每一个重要的瞬间都被好好看见。" },
  { id: "demo-person-005", name: "陈放", nickname: null, avatarUrl: null, cohort: { id: "cohort-2023", label: "2023 · 秋季届", year: 2023, sortOrder: 2 }, relationScope: "lineage", isFeatured: false, status: "active", mentorId: "demo-person-002", depth: 2, directStudentIds: [], role: "数据工程师", joinedAt: "2023-10-12", tags: ["数据", "工具"], bio: "把看不见的结构，整理成可被理解的秩序。" },
  { id: "demo-person-006", name: "唐宁", nickname: null, avatarUrl: null, cohort: { id: "cohort-2024", label: "2024 · 春季届", year: 2024, sortOrder: 3 }, relationScope: "lineage", isFeatured: false, status: "archived", mentorId: "demo-person-003", depth: 2, directStudentIds: [], role: "社会创新实践者", joinedAt: "2024-03-16", tags: ["公益", "组织"], bio: "在真实世界里验证每一个好想法。" }
];
const fallbackTree: Tree = { rootPersonId: "demo-person-001", nodes: fallbackPeople, edges: fallbackPeople.slice(1).map((person) => ({ id: `edge-${person.id}`, mentorId: person.mentorId!, studentId: person.id })), generatedAt: "2026-10-08T00:00:00.000Z", demo: true };

const tree = ref<Tree>(fallbackTree); const loading = ref(true); const apiFailed = ref(false); const query = ref(""); const selectedPerson = ref<Person | null>(null); const detailPerson = ref<Person | null>(null); const drawerOpen = ref(false); const expanded = ref<Record<string, boolean>>({}); const pathname = ref(window.location.pathname);
const people = computed(() => tree.value.nodes);
const rootPerson = computed(() => people.value.find((person) => person.id === tree.value.rootPersonId) ?? people.value[0] ?? null);
const groups = computed(() => { const map = new Map<string, { cohort: Cohort; members: Person[] }>(); people.value.filter((person) => person.id !== rootPerson.value?.id).forEach((person) => { const cohort = person.cohort ?? { id: "uncategorized", label: "未分届次", year: null, sortOrder: 99 }; const group = map.get(cohort.id) ?? { cohort, members: [] }; group.members.push(person); map.set(cohort.id, group); }); return [...map.values()].sort((a, b) => (a.cohort.sortOrder ?? 99) - (b.cohort.sortOrder ?? 99)); });
const matchingIds = computed(() => { const text = query.value.trim().toLocaleLowerCase(); if (!text) return new Set(people.value.map((person) => person.id)); return new Set(people.value.filter((person) => [person.name, person.nickname ?? "", person.role, person.cohort?.label ?? "", ...person.tags].join(" ").toLocaleLowerCase().includes(text)).map((person) => person.id)); });
const currentDetail = computed(() => { const match = pathname.value.match(/^\/person\/([^/]+)/); return match ? people.value.find((person) => person.id === match[1]) ?? null : null; });
const initials = (name: string) => name.replace(/\s+/g, "").slice(0, 2); const isVisible = (person: Person) => matchingIds.value.has(person.id); const relationLabel = (person: Person) => person.status === "archived" ? "已归档" : "在册成员";
function normaliseNode(node: Record<string, unknown>, index: number): Person { const source = fallbackPeople.find((person) => person.id === node.id) ?? fallbackPeople[index % fallbackPeople.length]; const cohort = node.cohort as Cohort | null | undefined; return { ...source, ...node, cohort: cohort ?? source.cohort, role: String(node.role ?? source.role), joinedAt: String(node.joinedAt ?? source.joinedAt), tags: Array.isArray(node.tags) ? node.tags as string[] : source.tags, bio: String(node.bio ?? source.bio) } as Person; }
async function loadTree() { loading.value = true; try { const response = await fetch("/api/tree"); if (!response.ok) throw new Error("tree unavailable"); const payload = await response.json() as { data?: { nodes?: Record<string, unknown>[]; edges?: Edge[]; rootPersonId?: string; generatedAt?: string; demo?: boolean } }; if (!payload.data?.nodes?.length) throw new Error("invalid tree"); tree.value = { rootPersonId: payload.data.rootPersonId ?? String(payload.data.nodes[0].id), nodes: payload.data.nodes.map(normaliseNode), edges: payload.data.edges ?? [], generatedAt: payload.data.generatedAt ?? new Date().toISOString(), demo: Boolean(payload.data.demo) }; } catch { apiFailed.value = true; tree.value = fallbackTree; } finally { expanded.value = Object.fromEntries(groups.value.map((group) => [group.cohort.id, true])); loading.value = false; } }
function openPreview(person: Person) { selectedPerson.value = person; drawerOpen.value = true; } function closePreview() { drawerOpen.value = false; } function toggleGroup(id: string) { expanded.value[id] = !expanded.value[id]; } function navigate(path: string) { window.history.pushState({}, "", path); pathname.value = path; drawerOpen.value = false; window.scrollTo({ top: 0, behavior: "smooth" }); } function onPopState() { pathname.value = window.location.pathname; drawerOpen.value = false; }
async function openDetail(person: Person) { detailPerson.value = person; try { const response = await fetch(`/api/people/${person.id}`); if (response.ok) { const payload = await response.json() as { data?: Record<string, unknown> }; if (payload.data) detailPerson.value = normaliseNode({ ...person, ...payload.data }, 0); } } catch { /* local record remains usable */ } }
function viewDetail(person: Person) { drawerOpen.value = false; navigate(`/person/${person.id}`); void openDetail(person); }
onMounted(() => { loadTree(); window.addEventListener("popstate", onPopState); if (currentDetail.value) openDetail(currentDetail.value); }); onUnmounted(() => window.removeEventListener("popstate", onPopState));
</script>

<template>
  <div class="app-shell">
    <header class="site-header"><a class="brand" href="/" @click.prevent="navigate('/')"><span class="brand-seal">谱</span><span class="brand-name">翻斗星谱<small>FANDOU LINEAGE ARCHIVE</small></span></a><div class="header-meta"><span class="status-dot"></span><span>{{ apiFailed ? "本地演示资料" : "实时档案连接" }}</span><button class="icon-button" title="只读预览" type="button">只读</button></div></header>
    <main v-if="!currentDetail" class="home-page"><section class="hero-row"><div><p class="eyebrow">THE LINEAGE ARCHIVE <span>01</span></p><h1>每一份传承，<em>都有迹可循。</em></h1><p class="hero-description">沿着师徒与同路人的连接，找到共同走过的路。这里是翻斗花园的成员树谱。</p></div><div class="hero-stat"><span>当前谱系</span><strong>{{ people.length }}<small>位成员</small></strong><span>{{ groups.length + 1 }} 个节点层级</span></div></section>
      <section class="toolbar"><label class="search-field"><span aria-hidden="true">⌕</span><input v-model="query" type="search" placeholder="搜索姓名、方向或届次" aria-label="搜索姓名、方向或届次" /><button v-if="query" type="button" aria-label="清空搜索" @click="query = ''">×</button></label><div class="toolbar-note"><span v-if="query">匹配 {{ matchingIds.size }} 位成员</span><span v-else>点击节点查看人物简介</span><span class="line-key"><i></i>师徒连接</span></div></section>
      <section class="tree-stage" aria-label="成员树谱"><div v-if="loading" class="state-message"><span class="loading-ring"></span>正在整理星谱</div><template v-else><div class="tree-intro"><span class="tree-label">ROOT NODE</span><span class="tree-date">更新于 {{ tree.generatedAt.slice(0, 10) }}</span></div><div v-if="rootPerson" class="root-node-wrap"><button class="person-node root-node" :class="{ dimmed: query && !isVisible(rootPerson), highlighted: query && isVisible(rootPerson) }" type="button" @click="openPreview(rootPerson)"><span class="avatar featured">{{ initials(rootPerson.name) }}</span><span class="node-info"><strong>{{ rootPerson.name }}</strong><small>{{ rootPerson.role }}</small></span><span class="node-mark">起点</span></button></div><div class="trunk-line" aria-hidden="true"></div><div class="cohort-grid"><article v-for="group in groups" :key="group.cohort.id" class="cohort-branch" :class="{ collapsed: expanded[group.cohort.id] === false }"><div class="branch-line" aria-hidden="true"></div><header class="cohort-heading"><div><span class="cohort-kicker">COHORT · {{ group.cohort.year ?? "—" }}</span><h2>{{ group.cohort.label }}</h2></div><button class="collapse-button" type="button" :aria-label="`${expanded[group.cohort.id] === false ? '展开' : '收起'} ${group.cohort.label}`" @click="toggleGroup(group.cohort.id)">{{ expanded[group.cohort.id] === false ? "+" : "−" }}</button></header><p class="cohort-caption">{{ group.members.length }} 位成员 · {{ group.members.some((member) => member.status === "archived") ? "含归档记录" : "持续连接" }}</p><div v-if="expanded[group.cohort.id] !== false" class="member-list"><button v-for="person in group.members" :key="person.id" class="person-node" :class="{ dimmed: query && !isVisible(person), highlighted: query && isVisible(person) }" type="button" @click="openPreview(person)"><span class="avatar" :class="person.status">{{ initials(person.name) }}</span><span class="node-info"><strong>{{ person.name }}</strong><small>{{ person.role }}</small></span><span class="node-arrow">↗</span></button></div></article></div><div v-if="query && matchingIds.size === 0" class="state-message empty">没有找到对应人物 <button type="button" @click="query = ''">清除搜索</button></div></template></section><footer class="page-footer"><span>翻斗星谱 · 早期演示版</span><span>资料仅用于界面演示，真实成员档案接入中</span></footer></main>
    <main v-else class="detail-page"><button class="back-link" type="button" @click="navigate('/')">← 返回星谱</button><div v-if="detailPerson || currentDetail" class="detail-layout"><section class="detail-intro"><p class="eyebrow">PERSONAL ARCHIVE <span>{{ (detailPerson || currentDetail)?.cohort?.label }}</span></p><div class="detail-avatar avatar featured">{{ initials((detailPerson || currentDetail)!.name) }}</div><h1>{{ (detailPerson || currentDetail)!.name }}</h1><p class="detail-role">{{ (detailPerson || currentDetail)!.role }}</p><div class="tag-row"><span v-for="tag in (detailPerson || currentDetail)!.tags" :key="tag" class="tag">{{ tag }}</span></div><span class="record-note"><i></i>{{ relationLabel(detailPerson || currentDetail!) }} · 演示档案</span></section><section class="detail-sections"><article class="detail-section"><span class="section-label">01 / 简介</span><p class="detail-copy">{{ (detailPerson || currentDetail)!.bio }}</p></article><article class="detail-section split-section"><div><span class="section-label">02 / 关系</span><h2>{{ (detailPerson || currentDetail)!.mentorId ? "沿着一条主线继续" : "谱系起点" }}</h2><p>{{ (detailPerson || currentDetail)!.mentorId ? "这位成员从上一代连接而来，并把自己的经验继续传给下一位。" : "从这里出发，连接仍在发生。" }}</p></div><div><span class="section-label">03 / 加入时间</span><h2>{{ (detailPerson || currentDetail)!.joinedAt }}</h2><p>{{ (detailPerson || currentDetail)!.cohort?.label }}</p></div></article><article class="detail-section"><span class="section-label">04 / 事迹与附件</span><div class="empty-detail"><span>＋</span><p>尚未添加事迹、荣誉或附件。</p></div></article></section></div><div v-else class="state-message">正在读取档案</div></main>
    <Transition name="drawer"><div v-if="drawerOpen && selectedPerson" class="drawer-backdrop" @click.self="closePreview"><aside class="person-drawer"><button class="drawer-close" type="button" aria-label="关闭人物简介" @click="closePreview">×</button><p class="eyebrow">QUICK VIEW <span>{{ selectedPerson.cohort?.label }}</span></p><div class="drawer-avatar avatar" :class="selectedPerson.status">{{ initials(selectedPerson.name) }}</div><h2>{{ selectedPerson.name }}</h2><p class="drawer-role">{{ selectedPerson.role }}</p><span class="record-note"><i></i>{{ relationLabel(selectedPerson) }}</span><div class="drawer-divider"></div><dl class="mini-facts"><div><dt>届次</dt><dd>{{ selectedPerson.cohort?.label ?? "未分届次" }}</dd></div><div><dt>加入时间</dt><dd>{{ selectedPerson.joinedAt }}</dd></div><div><dt>方向</dt><dd>{{ selectedPerson.tags.join(" · ") }}</dd></div></dl><p class="drawer-copy">{{ selectedPerson.bio }}</p><button class="primary-button" type="button" @click="viewDetail(selectedPerson)">查看完整档案 <span>↗</span></button></aside></div></Transition>
  </div>
</template>
