<script setup lang="ts">
import { computed, nextTick, onMounted, onUnmounted, ref, watch } from "vue";

type Status = "active" | "archived";
type Cohort = { id: string; label: string; year: number | null; sortOrder: number };
type Person = { id: string; name: string; nickname: string | null; avatarUrl: string | null; cohort: Cohort | null; relationScope: "lineage" | "cohort_guest"; isFeatured: boolean; status: Status; mentorId: string | null; depth: number | null; directStudentIds: string[]; role: string; joinedAt: string; tags: string[]; bio: string };
type Edge = { id: string; mentorId: string; studentId: string };
type Tree = { rootPersonId: string | null; nodes: Person[]; edges: Edge[]; generatedAt: string; demo: boolean };
type LinkSegment = { id: string; path: string; crossCohort: boolean };

const fallbackPeople: Person[] = [
  { id: "demo-person-001", name: "林砚", nickname: "砚叔", avatarUrl: null, cohort: { id: "cohort-2019", label: "2019 届", year: 2019, sortOrder: 0 }, relationScope: "lineage", isFeatured: true, status: "active", mentorId: null, depth: 0, directStudentIds: ["demo-person-002", "demo-person-003"], role: "发起人 / 产品顾问", joinedAt: "2019-06-18", tags: ["产品", "社区"], bio: "从一张白纸开始，记录每一次认真连接。" },
  { id: "demo-person-002", name: "周予安", nickname: null, avatarUrl: null, cohort: { id: "cohort-2021", label: "2021 届", year: 2021, sortOrder: 1 }, relationScope: "lineage", isFeatured: false, status: "active", mentorId: "demo-person-001", depth: 1, directStudentIds: ["demo-person-004", "demo-person-005"], role: "全栈开发者", joinedAt: "2021-03-22", tags: ["工程", "开源"], bio: "喜欢把复杂的问题拆成可以一起走的路。" },
  { id: "demo-person-003", name: "许棠", nickname: null, avatarUrl: null, cohort: { id: "cohort-2021", label: "2021 届", year: 2021, sortOrder: 1 }, relationScope: "lineage", isFeatured: false, status: "active", mentorId: "demo-person-001", depth: 1, directStudentIds: ["demo-person-006"], role: "研究与内容", joinedAt: "2021-04-08", tags: ["研究", "写作"], bio: "在资料、田野和人之间，寻找能被传下去的东西。" },
  { id: "demo-person-004", name: "苏禾", nickname: null, avatarUrl: null, cohort: { id: "cohort-2023", label: "2023 届", year: 2023, sortOrder: 2 }, relationScope: "lineage", isFeatured: false, status: "active", mentorId: "demo-person-002", depth: 2, directStudentIds: [], role: "交互设计师", joinedAt: "2023-09-01", tags: ["设计", "体验"], bio: "让每一个重要的瞬间都被好好看见。" },
  { id: "demo-person-005", name: "陈放", nickname: null, avatarUrl: null, cohort: { id: "cohort-2023", label: "2023 届", year: 2023, sortOrder: 2 }, relationScope: "lineage", isFeatured: false, status: "active", mentorId: "demo-person-002", depth: 2, directStudentIds: [], role: "数据工程师", joinedAt: "2023-10-12", tags: ["数据", "工具"], bio: "把看不见的结构，整理成可被理解的秩序。" },
  { id: "demo-person-006", name: "唐宁", nickname: null, avatarUrl: null, cohort: { id: "cohort-2024", label: "2024 届", year: 2024, sortOrder: 3 }, relationScope: "lineage", isFeatured: false, status: "archived", mentorId: "demo-person-003", depth: 2, directStudentIds: [], role: "社会创新实践者", joinedAt: "2024-03-16", tags: ["公益", "组织"], bio: "在真实世界里验证每一个好想法。" },
];
const fallbackTree: Tree = { rootPersonId: "demo-person-001", nodes: fallbackPeople, edges: fallbackPeople.slice(1).map((person) => ({ id: `edge-${person.id}`, mentorId: person.mentorId!, studentId: person.id })), generatedAt: "2026-10-08T00:00:00.000Z", demo: true };

const tree = ref<Tree>(fallbackTree); const loading = ref(true); const apiFailed = ref(false); const query = ref(""); const selectedPerson = ref<Person | null>(null); const detailPerson = ref<Person | null>(null); const pathname = ref(window.location.pathname); const expanded = ref<Record<string, boolean>>({}); const stageRef = ref<HTMLElement | null>(null); const nodeRefs = new Map<string, HTMLElement>(); const links = ref<LinkSegment[]>([]); const canvasSize = ref({ width: 0, height: 0 }); const popupPosition = ref({ left: 0, top: 0 });
const people = computed(() => tree.value.nodes);
const rootPerson = computed(() => people.value.find((person) => person.id === tree.value.rootPersonId) ?? people.value[0] ?? null);
const groups = computed(() => { const map = new Map<string, { cohort: Cohort; members: Person[] }>(); people.value.forEach((person) => { const cohort = person.cohort ?? { id: "uncategorized", label: "未分届次", year: null, sortOrder: 99 }; const group = map.get(cohort.id) ?? { cohort, members: [] }; group.members.push(person); map.set(cohort.id, group); }); return [...map.values()].sort((a, b) => (a.cohort.year ?? 9999) - (b.cohort.year ?? 9999) || (a.cohort.sortOrder ?? 99) - (b.cohort.sortOrder ?? 99)).map((group) => ({ ...group, members: group.members.sort((a, b) => (a.depth ?? 99) - (b.depth ?? 99) || a.name.localeCompare(b.name, "zh-CN")) })); });
const formatCohort = (cohort: Cohort | null) => cohort?.year ? `${cohort.year} 届` : "未分届次";
const matchingIds = computed(() => { const text = query.value.trim().toLocaleLowerCase(); if (!text) return new Set(people.value.map((person) => person.id)); return new Set(people.value.filter((person) => [person.name, person.nickname ?? "", person.role, formatCohort(person.cohort), ...person.tags].join(" ").toLocaleLowerCase().includes(text)).map((person) => person.id)); });
const currentDetail = computed(() => { const match = pathname.value.match(/^\/person\/([^/]+)/); return match ? people.value.find((person) => person.id === decodeURIComponent(match[1])) ?? null : null; });
const visibleLinks = computed(() => links.value.filter((link) => !query.value || matchingIds.value.has(link.id.split("::")[0]) || matchingIds.value.has(link.id.split("::")[1])));
const initials = (name: string) => name.replace(/\s+/g, "").slice(0, 2); const isVisible = (person: Person) => matchingIds.value.has(person.id); const relationLabel = (person: Person) => person.status === "archived" ? "已归档" : "在册成员"; const avatarClass = (person: Person) => person.isFeatured || person.id === rootPerson.value?.id ? "featured" : person.status;
function setNodeRef(id: string, element: Element | null) { if (element instanceof HTMLElement) nodeRefs.set(id, element); else nodeRefs.delete(id); }
function normaliseNode(node: Record<string, unknown>, index: number): Person { const source = fallbackPeople.find((person) => person.id === node.id) ?? fallbackPeople[index % fallbackPeople.length]; const rawCohort = node.cohort as Partial<Cohort> | null | undefined; const fallbackCohort = source.cohort; const rawYear = rawCohort?.year ?? String(rawCohort?.label ?? "").match(/\d{4}/)?.[0]; const year = rawYear ? Number(rawYear) : (fallbackCohort?.year ?? null); const cohort = rawCohort || fallbackCohort ? { ...(fallbackCohort ?? {}), ...(rawCohort ?? {}), id: year ? `cohort-${year}` : String(rawCohort?.id ?? fallbackCohort?.id ?? "uncategorized"), label: year ? `${year} 届` : "未分届次", year, sortOrder: Number(rawCohort?.sortOrder ?? fallbackCohort?.sortOrder ?? 99) } as Cohort : null; return { ...source, ...node, cohort, role: String(node.role ?? source.role), joinedAt: String(node.joinedAt ?? source.joinedAt), tags: Array.isArray(node.tags) ? node.tags as string[] : source.tags, bio: String(node.bio ?? source.bio) } as Person; }
async function loadTree() { loading.value = true; try { const response = await fetch("/api/tree"); if (!response.ok) throw new Error("tree unavailable"); const payload = await response.json() as { data?: { nodes?: Record<string, unknown>[]; edges?: Edge[]; rootPersonId?: string; generatedAt?: string; demo?: boolean } }; if (!payload.data?.nodes?.length) throw new Error("invalid tree"); tree.value = { rootPersonId: payload.data.rootPersonId ?? String(payload.data.nodes[0].id), nodes: payload.data.nodes.map(normaliseNode), edges: payload.data.edges ?? [], generatedAt: payload.data.generatedAt ?? new Date().toISOString(), demo: Boolean(payload.data.demo) }; } catch { apiFailed.value = true; tree.value = fallbackTree; } finally { expanded.value = Object.fromEntries(groups.value.map((group) => [group.cohort.id, true])); loading.value = false; await nextTick(); measureGraph(); } }
function toggleGroup(id: string) { expanded.value[id] = expanded.value[id] === false; if (selectedPerson.value?.cohort?.id === id) selectedPerson.value = null; nextTick(measureGraph); } function closePreview() { selectedPerson.value = null; } function navigate(path: string) { window.history.pushState({}, "", path); pathname.value = path; selectedPerson.value = null; detailPerson.value = null; window.scrollTo({ top: 0, behavior: "smooth" }); } function onPopState() { pathname.value = window.location.pathname; selectedPerson.value = null; if (currentDetail.value) void openDetail(currentDetail.value); }
async function openDetail(person: Person) { detailPerson.value = person; try { const response = await fetch(`/api/people/${person.id}`); if (response.ok) { const payload = await response.json() as { data?: Record<string, unknown> }; if (payload.data) detailPerson.value = normaliseNode({ ...person, ...payload.data }, 0); } } catch { /* local record remains usable */ } }
function viewDetail(person: Person) { navigate(`/person/${encodeURIComponent(person.id)}`); void openDetail(person); } function openPreview(person: Person) { selectedPerson.value = person; void nextTick().then(measurePopup); }
function measureGraph() { const stage = stageRef.value; if (!stage) return; const stageRect = stage.getBoundingClientRect(); canvasSize.value = { width: stageRect.width, height: stageRect.height }; links.value = tree.value.edges.flatMap((edge) => { const mentor = nodeRefs.get(edge.mentorId); const student = nodeRefs.get(edge.studentId); if (!mentor || !student) return []; const from = mentor.getBoundingClientRect(); const to = student.getBoundingClientRect(); const x1 = from.left - stageRect.left + from.width / 2; const y1 = from.top - stageRect.top + from.height / 2; const x2 = to.left - stageRect.left + to.width / 2; const y2 = to.top - stageRect.top + to.height / 2; const distance = Math.max(28, Math.abs(y2 - y1) * 0.42); return [{ id: `${edge.mentorId}::${edge.studentId}`, path: `M ${x1.toFixed(1)} ${y1.toFixed(1)} C ${x1.toFixed(1)} ${(y1 + distance).toFixed(1)}, ${x2.toFixed(1)} ${(y2 - distance).toFixed(1)}, ${x2.toFixed(1)} ${y2.toFixed(1)}`, crossCohort: Math.abs(y2 - y1) > 120 }]; }); }
function measurePopup() { const stage = stageRef.value; const person = selectedPerson.value; if (!stage || !person) return; const node = nodeRefs.get(person.id); if (!node) return; const stageRect = stage.getBoundingClientRect(); const nodeRect = node.getBoundingClientRect(); const left = nodeRect.left - stageRect.left + nodeRect.width / 2; const top = nodeRect.top - stageRect.top + nodeRect.height + 16; popupPosition.value = { left: Math.max(12, Math.min(left, Math.max(12, stageRect.width - 278))), top: Math.max(12, top) }; }
function onResize() { measureGraph(); if (selectedPerson.value) measurePopup(); } function onKeydown(event: KeyboardEvent) { if (event.key === "Escape") closePreview(); }
watch([query, expanded], () => nextTick(measureGraph), { deep: true }); onMounted(() => { void loadTree(); window.addEventListener("popstate", onPopState); window.addEventListener("resize", onResize); window.addEventListener("keydown", onKeydown); if (currentDetail.value) void openDetail(currentDetail.value); }); onUnmounted(() => { window.removeEventListener("popstate", onPopState); window.removeEventListener("resize", onResize); window.removeEventListener("keydown", onKeydown); });
</script>

<template>
  <div class="app-shell">
    <header class="site-header"><a class="brand" href="/" @click.prevent="navigate('/')"><span class="brand-sigil">✦</span><span class="brand-name">翻斗星谱<small>FANDOU LINEAGE ARCHIVE</small></span></a><div class="header-meta"><span class="status-dot"></span><span>{{ apiFailed ? "本地演示资料" : "星谱已连接" }}</span><span class="read-only">只读档案</span></div></header>
    <main v-if="!currentDetail" class="home-page">
      <section class="hero-row"><div><p class="eyebrow">THE LINEAGE CONSTELLATION <span>01</span></p><h1>让每颗星，<em>找到自己的轨道。</em></h1><p class="hero-description">上一届是下一届的师傅。同届成员并肩排列，跨届的牵引会沿着更长的轨迹抵达。</p></div><div class="hero-stat"><span>当前星谱</span><strong>{{ people.length }}<small>颗星</small></strong><span>{{ groups.length }} 个届次轨道</span></div></section>
      <section class="toolbar"><label class="search-field"><span aria-hidden="true">⌕</span><input v-model="query" type="search" placeholder="搜索姓名、方向或届次" aria-label="搜索姓名、方向或届次" /><button v-if="query" type="button" aria-label="清空搜索" @click="query = ''">×</button></label><div class="toolbar-note"><span v-if="query">匹配 {{ matchingIds.size }} 颗星</span><span v-else>谱系关系</span><span class="line-key"><i></i>师徒轨迹</span></div></section>
      <section ref="stageRef" class="star-stage" aria-label="成员星谱">
        <div v-if="loading" class="state-message"><span class="loading-ring"></span>正在整理星谱</div>
        <template v-else><svg class="line-layer" :viewBox="`0 0 ${canvasSize.width} ${canvasSize.height}`" preserveAspectRatio="none" aria-hidden="true"><path v-for="link in visibleLinks" :key="link.id" :d="link.path" :class="{ 'cross-cohort': link.crossCohort }" /></svg><div class="star-stage-meta"><span>ROOT TO CONSTELLATION</span><span>更新于 {{ tree.generatedAt.slice(0, 10) }}</span></div>
          <div v-for="group in groups" :key="group.cohort.id" class="cohort-row" :class="{ collapsed: expanded[group.cohort.id] === false }"><div class="orbit-heading"><span class="orbit-index">{{ String(group.cohort.year ?? "·").slice(-2) }}</span><div><span class="cohort-kicker">COHORT ORBIT</span><h2>{{ formatCohort(group.cohort) }}</h2></div><button class="collapse-button" type="button" :aria-label="`${expanded[group.cohort.id] === false ? '展开' : '收起'} ${formatCohort(group.cohort)}`" @click="toggleGroup(group.cohort.id)">{{ expanded[group.cohort.id] === false ? "+" : "−" }}</button></div><div v-if="expanded[group.cohort.id] !== false" class="star-row"><button v-for="person in group.members" :key="person.id" :ref="(el) => setNodeRef(person.id, el as Element)" class="star-node" :class="{ dimmed: query && !isVisible(person), highlighted: query && isVisible(person), root: person.id === rootPerson?.id }" type="button" :aria-label="`${person.name}，${formatCohort(person.cohort)}`" @click="openPreview(person)"><span class="star-avatar" :class="avatarClass(person)"><img v-if="person.avatarUrl" :src="person.avatarUrl" :alt="`${person.name}头像`" /><span v-else>{{ initials(person.name) }}</span></span><strong>{{ person.name }}</strong></button></div></div>
          <div v-if="query && matchingIds.size === 0" class="state-message empty">没有找到对应人物 <button type="button" @click="query = ''">清除搜索</button></div><div v-if="selectedPerson" class="quick-popover" :style="{ left: `${popupPosition.left}px`, top: `${popupPosition.top}px` }" role="dialog" :aria-label="`${selectedPerson.name}简介`"><button class="popover-close" type="button" aria-label="关闭简介" @click="closePreview">×</button><span class="popover-kicker">{{ formatCohort(selectedPerson.cohort) }} · {{ relationLabel(selectedPerson) }}</span><div class="popover-person"><span class="star-avatar mini" :class="avatarClass(selectedPerson)"><img v-if="selectedPerson.avatarUrl" :src="selectedPerson.avatarUrl" :alt="`${selectedPerson.name}头像`" /><span v-else>{{ initials(selectedPerson.name) }}</span></span><div><h2>{{ selectedPerson.name }}</h2><p>{{ selectedPerson.role }}</p></div></div><p class="popover-copy">{{ selectedPerson.bio }}</p><button class="popover-detail" type="button" @click="viewDetail(selectedPerson)">查看完整档案 <span>↗</span></button></div></template>
      </section><footer class="page-footer"><span>翻斗星谱 · 早期演示版</span><span>资料仅用于界面演示，真实成员档案接入中</span></footer>
    </main>
    <main v-else class="detail-page"><button class="back-link" type="button" @click="navigate('/')">← 返回星谱</button><div v-if="detailPerson || currentDetail" class="detail-layout"><section class="detail-intro"><p class="eyebrow">PERSONAL ARCHIVE <span>{{ formatCohort((detailPerson || currentDetail)!.cohort) }}</span></p><div class="detail-avatar star-avatar featured">{{ initials((detailPerson || currentDetail)!.name) }}</div><h1>{{ (detailPerson || currentDetail)!.name }}</h1><p class="detail-role">{{ (detailPerson || currentDetail)!.role }}</p><div class="tag-row"><span v-for="tag in (detailPerson || currentDetail)!.tags" :key="tag" class="tag">{{ tag }}</span></div><span class="record-note"><i></i>{{ relationLabel(detailPerson || currentDetail!) }} · 演示档案</span></section><section class="detail-sections"><article class="detail-section"><span class="section-label">01 / 简介</span><p class="detail-copy">{{ (detailPerson || currentDetail)!.bio }}</p></article><article class="detail-section split-section"><div><span class="section-label">02 / 关系</span><h2>{{ (detailPerson || currentDetail)!.mentorId ? "沿着一条主线继续" : "谱系起点" }}</h2><p>{{ (detailPerson || currentDetail)!.mentorId ? "这位成员从上一届连接而来，并把自己的经验继续传给下一位。" : "从这里出发，连接仍在发生。" }}</p></div><div><span class="section-label">03 / 加入时间</span><h2>{{ (detailPerson || currentDetail)!.joinedAt }}</h2><p>{{ formatCohort((detailPerson || currentDetail)!.cohort) }}</p></div></article><article class="detail-section"><span class="section-label">04 / 事迹与附件</span><div class="empty-detail"><span>＋</span><p>尚未添加事迹、荣誉或附件。</p></div></article></section></div><div v-else class="state-message">正在读取档案</div></main>
  </div>
</template>
